# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 04:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('B', 'Banarse'), ('D1', 'Descarga_1'), ('D2', 'Descarga_2'), ('D3', 'Descarga_3'), ('LD', 'Lavarse Dientes'), ('LM', 'Lavarse Manos'), ('LC', 'Lavarse Cara')], max_length=25)),
                ('bathroom_saving', models.BooleanField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(max_length=25)),
                ('water_amount_container', models.FloatField()),
                ('wateringcan', models.CharField(max_length=25)),
                ('water_amount_wateringcan', models.FloatField()),
                ('bathtub', models.CharField(max_length=25)),
                ('water_amount_bathtub', models.FloatField()),
                ('handwash', models.CharField(max_length=25)),
                ('water_amount_handwash', models.FloatField()),
                ('date', models.DateField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('date', models.DateField(blank=True, null=True)),
                ('concluded', models.BooleanField()),
                ('liters_consumed', models.FloatField()),
                ('created', models.DateField()),
                ('action_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hackaton.Action')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateField()),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('liter_quantity', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('action_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hackaton.Action')),
            ],
        ),
        migrations.CreateModel(
            name='User_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hackaton.Group')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Medal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('medal_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hackaton.Medal')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
